# Generated by Django 6.0.5 on 2026-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
