# Generated by Django 6.0.5 on 2026-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_note_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='daily_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
