# Generated by Django 6.0.5 on 2026-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='daily_note',
        ),
        migrations.AddField(
            model_name='student',
            name='dashboard_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
